/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio1;

import static com.sun.glass.events.KeyEvent.VK_BACKSPACE;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Javier
 */
public class Chef extends javax.swing.JFrame {

    /**
     * Creates new form Chef
     */
    static int filas;

    public Chef() {
        initComponents();
        crearFichero();
        cantplatos = consultarFichero();
        generarTabla(ChefTabla, cantplatos);
        ChefTabla.setDefaultEditor(Object.class, null);
        mostrarFichero();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AñadirPlatosFrame.setResizable(false);
        AñadirPlato.setEnabled(false);
        AñadirPlatosFrame.setSize(400, 390);
        RevisarBodegaFrame.setResizable(false);
        RevisarBodegaFrame.setSize(450, 354);
        aib.setEnabled(false);
        TablaBodega.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AñadirPlatosFrame = new javax.swing.JFrame();
        NombreTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        IngTabla = new javax.swing.JTable();
        tf1 = new javax.swing.JTextField();
        aib = new javax.swing.JButton();
        AñadirPlato = new javax.swing.JButton();
        PrecioTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RevisarBodegaFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaBodega = new javax.swing.JTable();
        RegresarBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChefTabla = new javax.swing.JTable();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();

        AñadirPlatosFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AñadirPlatosFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                AñadirPlatosFrameWindowClosed(evt);
            }
        });

        NombreTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTFKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre del plato");

        jLabel2.setText("Cant. de ingr. que tiene el plato:");

        IngTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrediente", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(IngTabla);
        if (IngTabla.getColumnModel().getColumnCount() > 0) {
            IngTabla.getColumnModel().getColumn(0).setResizable(false);
            IngTabla.getColumnModel().getColumn(1).setResizable(false);
        }

        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        aib.setText("Agregar");
        aib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aibMouseClicked(evt);
            }
        });

        AñadirPlato.setText("Añadir Plato");
        AñadirPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirPlatoMouseClicked(evt);
            }
        });
        AñadirPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirPlatoActionPerformed(evt);
            }
        });

        PrecioTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioTFKeyTyped(evt);
            }
        });

        jLabel3.setText("Precio del plato");

        javax.swing.GroupLayout AñadirPlatosFrameLayout = new javax.swing.GroupLayout(AñadirPlatosFrame.getContentPane());
        AñadirPlatosFrame.getContentPane().setLayout(AñadirPlatosFrameLayout);
        AñadirPlatosFrameLayout.setHorizontalGroup(
            AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AñadirPlatosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AñadirPlato)
                    .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(AñadirPlatosFrameLayout.createSequentialGroup()
                            .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AñadirPlatosFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(26, 26, 26)
                                    .addComponent(PrecioTF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AñadirPlatosFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(NombreTF))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AñadirPlatosFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(aib, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AñadirPlatosFrameLayout.setVerticalGroup(
            AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AñadirPlatosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PrecioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AñadirPlatosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aib))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AñadirPlato)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        RevisarBodegaFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        RevisarBodegaFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                RevisarBodegaFrameWindowClosed(evt);
            }
        });

        TablaBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ingrediente", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaBodega);

        RegresarBt.setText("Regresar");
        RegresarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RevisarBodegaFrameLayout = new javax.swing.GroupLayout(RevisarBodegaFrame.getContentPane());
        RevisarBodegaFrame.getContentPane().setLayout(RevisarBodegaFrameLayout);
        RevisarBodegaFrameLayout.setHorizontalGroup(
            RevisarBodegaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevisarBodegaFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RevisarBodegaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RevisarBodegaFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegresarBt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        RevisarBodegaFrameLayout.setVerticalGroup(
            RevisarBodegaFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RevisarBodegaFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegresarBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ChefTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Ingredientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ChefTabla);

        bt1.setText("Añadir nuevo plato al menú");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("Revisar Bodega");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static int s = 0;

    void generarTabla(JTable tabla, int cant) {
        DefaultTableModel model = new DefaultTableModel(cant, 2);
        tabla.setModel(model);
        mostrarFichero();
        JTableHeader th = ChefTabla.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc = tcm.getColumn(0);
        tc.setHeaderValue("Plato: ");
        tc.setResizable(false);
        TableColumn tc1 = tcm.getColumn(1);
        tc1.setHeaderValue("Ingredientes: ");
        tc1.setResizable(false);
        th.repaint();
        aib.setEnabled(false);
    }
    
    void generarTabla1(JTable tabla, int cant) {
        DefaultTableModel model = new DefaultTableModel(cant, 2);
        tabla.setModel(model);
        mostrarFichero();
        JTableHeader th = tabla.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc = tcm.getColumn(0);
        tc.setHeaderValue("Ingrediente: ");
        tc.setResizable(false);
        TableColumn tc1 = tcm.getColumn(1);
        tc1.setHeaderValue("Cantidad: ");
        tc1.setResizable(false);
        th.repaint();
        aib.setEnabled(false);
    }

    public static void crearFichero() {
        FileWriter fw = null;
        try {

            File archivo = new File("platos.txt");

            if (archivo.exists()) {
                s = 1;
            } else {
                fw = new FileWriter("platos.txt");
                PrintWriter pw = new PrintWriter(fw);
                escribirFichero(pw);
                s = 1;
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fw != null) {
                    fw.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public static void escribirFichero(PrintWriter pw) throws Exception {
        filas = Integer.parseInt(tf1.getText());
        String opcion;
        int z = 0;
        opcion = NombreTF.getText();
        pw.print(opcion + ", ");
        for (int i = 0; i < filas - 1; i++) {
            opcion = IngTabla.getValueAt(z, 0).toString();
            pw.print(opcion + ", ");
            z++;
        }
        if (z == filas - 1) {
            opcion = IngTabla.getValueAt(z, 0).toString();
            pw.print(opcion);
            z++;
        }
        if (PrecioTF.getText() != null) {
            opcion = PrecioTF.getText();
            pw.print(", "+opcion);
        }
        pw.println();
    }

    public static void ingresarFichero() {
        FileWriter fw = null;
        try {
            fw = new FileWriter("platos.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            escribirFichero(pw);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fw != null) {
                    fw.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    public static void mostrarFichero() {
        FileReader fr = null;
        try {
            File fichero = new File("platos.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            leerFichero(br);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public static void mostrarFichero1() {
        FileReader fr = null;
        try {
            File fichero = new File("bodega.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            leerFichero1(br);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }

    static int cantplatos;

    public static void leerFichero(BufferedReader br) throws Exception {
        String linea;
        int sw = 0;
        int z = 0;
        linea = br.readLine();
        String plato;
        String ingr = "";
        while (linea != null) {
            sw = 0;
            for (int i = 0; i < linea.length(); i++) {
                System.out.println("ChatAt(i): " + linea.charAt(i));
                if (linea.charAt(i) == ',' && sw == 0) {
                    plato = linea.substring(0, i);
                    ChefTabla.setValueAt(plato, z, 0);
                    sw = 1;
                } else if (sw == 1) {
                    ingr = linea.substring(i, linea.length());
                    ChefTabla.setValueAt(ingr, z, 1);
                    sw = 2;
                    z++;
                }
            }
            linea = br.readLine();
        }
    }
    
    public static void leerFichero1(BufferedReader br) throws Exception {
        String linea;
        int sw = 0;
        int z = 0;
        linea = br.readLine();
        String plato;
        String ingr = "";
        while (linea != null) {
            sw = 0;
            for (int i = 0; i < linea.length(); i++) {
                System.out.println("ChatAt(i): " + linea.charAt(i));
                if (linea.charAt(i) == ',' && sw == 0) {
                    plato = linea.substring(0, i);
                    TablaBodega.setValueAt(plato, z, 0);
                    sw = 1;
                } else if (sw == 1) {
                    ingr = linea.substring(i, linea.length());
                    TablaBodega.setValueAt(ingr, z, 1);
                    sw = 2;
                    z++;
                }
            }
            linea = br.readLine();
        }
    }

    public static int consultarFichero() {
        FileReader fr = null;
        int c = 0;
        try {
            File fichero = new File("platos.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            linea = br.readLine();
            while (linea != null) {
                c = c + 1;
                linea = br.readLine();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        return c;
    }
    
    public static int consultarFichero1() {
        FileReader fr = null;
        int c = 0;
        try {
            File fichero = new File("bodega.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            linea = br.readLine();
            while (linea != null) {
                c = c + 1;
                linea = br.readLine();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        return c;
    }
    
    
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        AñadirPlatosFrame.setLocationRelativeTo(this);
        AñadirPlatosFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JOptionPane.showMessageDialog(null, "Gracias por su trabajo, vuelva pronto!", "Cerrar Sesion", 1);
        Login as = new Login();
        as.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void AñadirPlatosFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AñadirPlatosFrameWindowClosed
        this.setVisible(true);
        NombreTF.setText(null);
        tf1.setText(null);
        PrecioTF.setText(null);
        aib.setEnabled(false);
        AñadirPlato.setEnabled(false);
        DefaultTableModel model = new DefaultTableModel();
        IngTabla.setModel(model);
    }//GEN-LAST:event_AñadirPlatosFrameWindowClosed

    private void AñadirPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirPlatoMouseClicked
        AñadirPlato.setEnabled(true);
        filas = Integer.parseInt(tf1.getText());
        crearFichero();
        ingresarFichero();
        this.setVisible(true);
        AñadirPlatosFrame.setVisible(false);
        cantplatos = consultarFichero();
        generarTabla(ChefTabla, cantplatos);
        AñadirPlato.setEnabled(false);
    }//GEN-LAST:event_AñadirPlatoMouseClicked

    private void aibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aibMouseClicked
        try {
            filas = Integer.parseInt(tf1.getText());
            DefaultTableModel model = new DefaultTableModel(filas, 1);
            IngTabla.setModel(model);
            JTableHeader th = IngTabla.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue("Ingredientes: ");
            tc.setResizable(false);
            th.repaint();
            AñadirPlato.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Campo vacio/Invalido");
            tf1.setText(null);
            AñadirPlato.setEnabled(false);
        }
    }//GEN-LAST:event_aibMouseClicked

    private void NombreTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTFKeyTyped
        char e = evt.getKeyChar();
        if (!Character.isLetter(e) && e != evt.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten letras");
            tf1.setEditable(false);
        } else {
            tf1.setEditable(true);
        }
        if (NombreTF.getText().equals(null)) {
            aib.setEnabled(false);
            tf1.setEditable(false);
        }
        if (e == evt.VK_BACK_SPACE && NombreTF.getText().isEmpty()) {
            aib.setEnabled(false);
        }
    }//GEN-LAST:event_NombreTFKeyTyped

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        char e = evt.getKeyChar();
        if (!Character.isDigit(e) && e != evt.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permiten numeros");
            aib.setEnabled(false);
        } else {
            aib.setEnabled(true);
        }
        if (e == evt.VK_BACK_SPACE && tf1.getText().isEmpty()) {
            aib.setEnabled(false);
        }
        if (vericero(tf1.getText()) == 0 && e == evt.VK_BACK_SPACE) {
            aib.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Numero no valido");
            evt.consume();
        }
    }//GEN-LAST:event_tf1KeyTyped

    private void PrecioTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTFKeyTyped

    private void AñadirPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadirPlatoActionPerformed

    static int cantingr;
    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        RevisarBodegaFrame.setLocationRelativeTo(this);
        RevisarBodegaFrame.setVisible(true);
        this.setVisible(false);
        cantingr = consultarFichero1();
        generarTabla1(TablaBodega, cantingr);
        mostrarFichero1();
    }//GEN-LAST:event_bt2ActionPerformed

    private void RegresarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        RevisarBodegaFrame.setVisible(false);
    }//GEN-LAST:event_RegresarBtActionPerformed

    private void RevisarBodegaFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RevisarBodegaFrameWindowClosed
        // TODO add your handling code here:
        this.setVisible(true);
        RevisarBodegaFrame.setVisible(false);
    }//GEN-LAST:event_RevisarBodegaFrameWindowClosed

    int vericero(String f) {
        try {
            return Integer.parseInt(f);
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirPlato;
    private javax.swing.JFrame AñadirPlatosFrame;
    public static javax.swing.JTable ChefTabla;
    public static javax.swing.JTable IngTabla;
    public static javax.swing.JTextField NombreTF;
    public static javax.swing.JTextField PrecioTF;
    private javax.swing.JButton RegresarBt;
    private javax.swing.JFrame RevisarBodegaFrame;
    public static javax.swing.JTable TablaBodega;
    private javax.swing.JButton aib;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
