/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio1;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javier
 */
public class Cocina extends javax.swing.JFrame {

    /**
     * Creates new form Cocina
     */
    public Cocina() {
        initComponents();
        actualizar();
        this.setLocationRelativeTo(null);
        TablaCocina.setDefaultEditor(Object.class, null);
        bt1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCocina = new javax.swing.JTable();
        bt1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        TablaCocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pedido", "Mesa"
            }
        ));
        TablaCocina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TablaCocinaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCocina);
        if (TablaCocina.getColumnModel().getColumnCount() > 0) {
            TablaCocina.getColumnModel().getColumn(0).setResizable(false);
            TablaCocina.getColumnModel().getColumn(1).setResizable(false);
        }

        bt1.setText("Orden Lista");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt1)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int x2, y2, m;

    boolean verificareclamopedido(int mesa) {
        for (int i = 0; i < MeserosTabla.mesa.size(); i++) {
            if (((Mesas) MeserosTabla.mesa.geto(i)).numero == mesa && ((Mesas) MeserosTabla.mesa.geto(i)).estado.equals("reclamado")) {
                return true;
            }
        }
        return false;
    }

    void actualizar() {
        for (int i = 0; i < Menu.Pedidos.size(); i++) {
            int numeromesa = ((Pedido) Menu.Pedidos.geto(i)).mesa;
            if (verificareclamopedido(numeromesa)==false) {
                for (int j = 0; j < 2; j++) {
                    if (j == 0) {
                        TablaCocina.setValueAt(((Pedido) Menu.Pedidos.geto(i)).pedido, i, j);
                    } else {
                        TablaCocina.setValueAt(((Pedido) Menu.Pedidos.geto(i)).mesa, i, j);
                    }
                }
            }
        }
        TablaCocina.updateUI();
    }

    void ActBodega() {
        consultarFichero();
    }

    public static void consultarFichero() {
        FileReader fr = null;
        FileWriter fw = null;
        int c = 0;
        try {
            File fichero = new File("bodega.txt");
            fw = new FileWriter("bodega.txt", true);
            PrintWriter pw = new PrintWriter(fw);
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            linea = br.readLine();
            String linea1;
            pw.println();
            int i = 0;
            while (linea != null) {
                linea = br.readLine();
                while (i < linea.length()) {
                    if (linea.charAt(i) == ',') {
                        String plato = linea.substring(i);
                        if (plato == pedido) {
                            int cantidad1 = Integer.parseInt(linea.substring(i, linea.length()));
                            cantidad1 = cantidad1 - cantidad;
                            linea1 = plato + (", " + cantidad1);
                            break;
                        }else{
                            linea1 = plato;
                            escribirFichero(pw,linea1);
                        }
                    }
                    i++;
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }
    
    public static int consultarFichero1() {
        FileReader fr = null;
        int c = 0;
        try {
            File fichero = new File("bodega.txt");
            fr = new FileReader(fichero);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            linea = br.readLine();
            while (linea != null) {
                c = c + 1;
                linea = br.readLine();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (fr != null) {
                    fr.close();
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        return c;
    }
    static int filas;
    
    public static void escribirFichero(PrintWriter pw, String linea) throws Exception {
        File arc = new File("bodega.txt");
        filas = consultarFichero1();
        String opcion;
        int z = 0;
        opcion = linea;
        pw.print(opcion);
    }

    static int cantidad;
    static String pedido;

    void getstrpedido(int mesa1) {
        int j = 0;
        String pe = "";
        Pedido p = new Pedido();
        for (int i = 0; i < Menu.Pedidos.size(); i++) {
            if (((Pedido) Menu.Pedidos.geto(i)).mesa == mesa1) {
                pe = ((Pedido) Menu.Pedidos.geto(i)).pedido;
                p = ((Pedido) Menu.Pedidos.geto(i));
            }
        }
        for (int i = 0; i < pe.length(); i++) {
            try {
                int f = i + 1;
                if (Integer.parseInt(pe.substring(i, f)) >= 1) {
                    int f2 = i - 1;
                    pedido = pe.substring(j, f2);
                    cantidad = Integer.parseInt(pe.substring(i, f));
                    j = f + 1;
                }
            } catch (Exception e) {

            }
        }
    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JOptionPane.showMessageDialog(null, "Gracias por su trabajo, vuelva pronto!", "Cerrar Sesion", 1);
        Login as = new Login();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void TablaCocinaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCocinaMouseReleased
        x2 = TablaCocina.rowAtPoint(evt.getPoint());
        y2 = TablaCocina.columnAtPoint(evt.getPoint());
        bt1.setEnabled(true);
        try {
            m = ((int) TablaCocina.getValueAt(x2, 1)) - 1;
        } catch (Exception e) {
            bt1.setEnabled(false);
        }
    }//GEN-LAST:event_TablaCocinaMouseReleased

    private void bt1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseReleased
        if (((Mesas) MeserosTabla.mesa.geto(m)).estado.equals("pro")) {
            ((Mesas) MeserosTabla.mesa.geto(m)).estado = "listo";
            bt1.setEnabled(false);
            String m1 = TablaCocina.getValueAt(x2, 0).toString();
            int sw = 0;
            for (int i = 0; i < Menu.Pedidos.size(); i++) {
                if (((Pedido) Menu.Pedidos.geto(i)).pedido.equals(m1)) {
                    getstrpedido(m + 1);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error, el pedido aun no se ha reclamado!");
        }
    }//GEN-LAST:event_bt1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaCocina;
    private javax.swing.JButton bt1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
