/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio1;

import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import static laboratorio1.Chef.ChefTabla;

/**
 *
 * @author Johnny
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    static List Users = new List();
    static List Passwords = new List();
    static String ActualUser;

    public Login() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        if (Users.size() == 0) {
            Users.add("Admin");
            Passwords.add("1234");
            Users.add("Chef");
            Passwords.add("1234");
            Users.add("Waiter1");
            Passwords.add("12345");
            Users.add("Waiter2");
            Passwords.add("12346");
            Users.add("Waiter3");
            Passwords.add("12347");
            Users.add("Waiter4");
            Passwords.add("12348");
            Users.add("Cocina");
            Passwords.add("1");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablacuenta = new javax.swing.JTable();
        bt2 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        mb1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        mi1 = new javax.swing.JMenuItem();

        Tablacuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cuenta", "Clave"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tablacuenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tablacuenta);
        if (Tablacuenta.getColumnModel().getColumnCount() > 0) {
            Tablacuenta.getColumnModel().getColumn(0).setResizable(false);
            Tablacuenta.getColumnModel().getColumn(1).setResizable(false);
        }

        bt2.setText("Cerrar");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd1Layout = new javax.swing.GroupLayout(jd1.getContentPane());
        jd1.getContentPane().setLayout(jd1Layout);
        jd1Layout.setHorizontalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jd1Layout.setVerticalGroup(
            jd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt2)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb1.setText("Usuario:");

        lb2.setText("Contraseña:");

        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        bt1.setText("Iniciar Sesion");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        menu1.setText("Cuentas");
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu1MousePressed(evt);
            }
        });

        mi1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mi1.setText("Mostrar Cuentas");
        mi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi1ActionPerformed(evt);
            }
        });
        menu1.add(mi1);

        mb1.add(menu1);

        setJMenuBar(mb1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb2)
                            .addComponent(lb1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf1)
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(pf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi1ActionPerformed
        jd1.setVisible(true);
        jd1.setLocation(543, 230);
        jd1.setResizable(false);
        jd1.setSize(279, 300);
        for (int i = 0; i < Users.size(); i++) {
            for (int j = 0; j < Tablacuenta.getColumnCount(); j++) {
                Tablacuenta.setValueAt(Users.gets(i), i, 0);
                Tablacuenta.setValueAt(Passwords.gets(i), i, 1);
            }
        }
    }//GEN-LAST:event_mi1ActionPerformed

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1KeyTyped

    boolean verificar() {
        if (ActualUser.equals("Waiter1") || ActualUser.equals("Waiter2") || ActualUser.equals("Waiter3") || ActualUser.equals("Waiter4")) {
            return true;
        } else {
            return false;
        }
    }

    boolean verificar2() {
        if (ActualUser.equals("Chef")) {
            return true;
        } else {
            return false;
        }
    }

    boolean verificar3() {
        if (ActualUser.equals("Cocina")) {
            return true;
        } else {
            return false;
        }
    }
    
    boolean verificar4() {
        if (ActualUser.equals("Admin")) {
            return true;
        } else {
            return false;
        }
    }

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        String user = tf1.getText();
        String password = pf1.getText();
        int sw = 0, z = 0;
        ActualUser = "";
        if (Users.contains(user)) {
            while (z < Users.size() && sw == 0) {
                if (Users.gets(z).equals(user)) {
                    if (password.equals(Passwords.gets(z))) {
                        JOptionPane.showMessageDialog(null, "Sesion inciada con exito!", "Iniciar Sesion", 1);
                        sw = 1;
                        ActualUser = Users.gets(z);
                    }
                }
                z++;
            }
            if (verificar()) {
                MeserosTabla ms = new MeserosTabla();
                ms.setVisible(true);
                this.dispose();
                jd1.dispose();
            }
            if (verificar2()) {
                Chef ch = new Chef();
                ch.setVisible(true);
                this.dispose();
                jd1.dispose();
            }
            if (verificar3()) {
                Cocina c=new Cocina();
                c.setVisible(true);
                this.dispose();
                jd1.dispose();
            }
            if (verificar4()) {
                Admin a = new Admin();
                a.setVisible(true);
                this.dispose();
                jd1.dispose();
            }
        }
        if ((!Users.contains(user)) || sw == 0) {
            JOptionPane.showMessageDialog(null, "Usuario/Contraseña incorrecto(s)", "Error", 0);
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked

    }//GEN-LAST:event_menu1MouseClicked

    private void menu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MousePressed

    }//GEN-LAST:event_menu1MousePressed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        jd1.dispose();
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablacuenta;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JMenuBar mb1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenuItem mi1;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
