/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio1;

import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Johnny
 */
public class MeserosTabla extends javax.swing.JFrame {

    /**
     * Creates new form MeserosTabla
     */
    static int sw = 0;
    static int x, y;
    static List mesa = new List();
    static List mesaus = new List();
    static int ac;
    static boolean click = false;

    public MeserosTabla() {
        initComponents();
        lb3.setText(Login.ActualUser);
        this.setLocationRelativeTo(null);
        if (mesa.size() == 0) {
            llenar();
        } else {
            actualizar();
        }
        TablaMeseros.setDefaultRenderer(Object.class, new RenderTabla());
        TablaMeseros.updateUI();
        lb6.setText("" + ac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMeseros = new javax.swing.JTable();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lb1.setText("Tabla de Mesas");

        TablaMeseros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Mesa", "Disponibilidad", "Estado de Pedido", "Mesero a Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaMeseros.setRowSelectionAllowed(false);
        TablaMeseros.getTableHeader().setReorderingAllowed(false);
        TablaMeseros.setUpdateSelectionOnSort(false);
        TablaMeseros.setVerifyInputWhenFocusTarget(false);
        TablaMeseros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMeserosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaMeseros);
        if (TablaMeseros.getColumnModel().getColumnCount() > 0) {
            TablaMeseros.getColumnModel().getColumn(0).setResizable(false);
            TablaMeseros.getColumnModel().getColumn(1).setResizable(false);
            TablaMeseros.getColumnModel().getColumn(2).setResizable(false);
            TablaMeseros.getColumnModel().getColumn(3).setResizable(false);
        }

        lb2.setText("Mesero:");

        lb4.setText("Cambiar Cuenta:");

        bt1.setText("Salir");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        lb5.setText("Mesas a Cargo:");

        lb7.setText("de 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb7)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb1)
                        .addGap(177, 177, 177))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb2)
                            .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb5)
                                    .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb4)
                                    .addComponent(bt1)))
                            .addComponent(lb7))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void actualizar() {
        ac = 0;
        for (int i = 0; i < 20; i++) {
            TablaMeseros.setValueAt(((Mesas) mesa.geto(i)).numero, i, 0);
            TablaMeseros.setValueAt((String) ((Mesas) mesa.geto(i)).mesero, i, 3);
            if (((Mesas) mesa.geto(i)).mesero.equals(Login.ActualUser)) {
                ac++;
            }
        }
        TablaMeseros.updateUI();
    }

    public void llenar() {
        for (int i = 0; i < 20; i++) {
            Mesas mesas = new Mesas((i + 1));
            mesa.add(mesas);
            ((Mesas) mesa.geto(i)).dispo = "si";
            ((Mesas) mesa.geto(i)).estado = "noa";
            TablaMeseros.setValueAt(((Mesas) mesa.geto(i)).numero, i, 0);
        }
    }

    private void TablaMeserosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMeserosMouseClicked
        if (click == false) {
            x = TablaMeseros.rowAtPoint(evt.getPoint());
            y = TablaMeseros.columnAtPoint(evt.getPoint());
            if (y == 1) {
                if (ac < 5) {
                    if (mesaus.contains((Mesas) mesa.geto(x))) {
                        JOptionPane.showMessageDialog(null, "La mesa esta siendo atendida");
                    } else {
                        mesaus.add((Mesas) mesa.geto(x));
                        ((Mesas) mesa.geto(x)).mesero = Login.ActualUser;
                        ac++;
                        ((Mesas) mesa.geto(x)).dispo = "no";
                        lb6.setText("" + ac);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ha alcanzado el numero maximo de mesas atendidas");
                }
            }
            if (y == 2 && ((Mesas) mesa.geto(x)).mesero.equals(Login.ActualUser)) {
                Menu menu = new Menu();
                menu.setVisible(true);
                if (((Mesas) mesa.geto(x)).estado.equals("pro") || ((Mesas) mesa.geto(x)).estado.equals("listo")) {
                    menu.actualizar2();
                }
                click = true;
            }
        }
        TablaMeseros.updateUI();
        actualizar();
    }//GEN-LAST:event_TablaMeserosMouseClicked

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por su trabajo, vuelva pronto!", "Cerrar Sesion", 1);
        Login asad = new Login();
        this.setVisible(false);
        asad.setVisible(true);
    }//GEN-LAST:event_bt1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        JOptionPane.showMessageDialog(null, "Gracias por su trabajo, vuelva pronto!", "Cerrar Sesion", 1);
        Login as=new Login();
        as.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeserosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeserosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeserosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeserosTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeserosTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaMeseros;
    private javax.swing.JButton bt1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    public static javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    public static javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    // End of variables declaration//GEN-END:variables
}
